version: '3.5'

services:
  application-db:
    image: postgres
    container_name: application-db
    ports:
      - "5432:5432"
    networks:
      - application-server
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: items

networks:
  application-server:
    driver: bridge